### ISSUE TITLE
libffi fails to build with python 3.4

### ISSUE THREAD

**Issue by accel2k** [wingtk/gvsbuild#214]
os.scandir introduced in python 3.5, may be we need to update readme.md?

> Traceback (most recent call last):
>   File "E:\gtk-build\github\gtk-win32\gvsbuild\utils\builder.py", line 325, in build
>     self.__build_one(p)
>   File "E:\gtk-build\github\gtk-win32\gvsbuild\utils\builder.py", line 376, in __build_one
>     proj.prepare_build_dir()
>   File "E:\gtk-build\github\gtk-win32\gvsbuild\utils\base_project.py", line 121, in prepare_build_dir
>     self.unpack()
>   File "E:\gtk-build\github\gtk-win32\gvsbuild\utils\base_expanders.py", line 213, in unpack
>     self.create_zip()
>   File "E:\gtk-build\github\gtk-win32\gvsbuild\utils\base_expanders.py", line 201, in create_zip
>     all_files = dirlist2set(self.build_dir, add_dirs=True)
>   File "E:\gtk-build\github\gtk-win32\gvsbuild\utils\base_expanders.py", line 140, in dirlist2set
>     _load_single_dir(st_dir, rt)
>   File "E:\gtk-build\github\gtk-win32\gvsbuild\utils\base_expanders.py", line 130, in _load_single_dir
>     for cf in os.scandir(dir_name):
> AttributeError: 'module' object has no attribute 'scandir'
> Error: libffi build failed
> 
>

**Comment by nacho** [comment]
In the readme we have that we require 3.6 and 3.4

**Comment by accel2k** [comment]
My bad, I thought it requires python 3.4 for VS13 or 3.6 for others. Anyway, it's not clear from README which version should be used with build.py. By the way, I successfully built glib and gtk3 (both 32 and 64 bit) with VS13 without python 3.4. It also doesn't match with README.
